### ISSUE TITLE
Example of NMAP Results

### ISSUE THREAD

**Issue by DrTableBasse** [hackertarget/nmap-did-what#4]
Hello 👋 

Do you have an example of results of your nmap and do you have the CLI you used for this repository ?

Thx a lot !

**Comment by peter-hackertarget** [comment]
Example command is in article detailing the [Grafana Nmap Project](https://hackertarget.com/nmap-dashboard-with-grafana/).

Use the command from the article and you will get some results. Test against scanme.nmap.org if you have no open ports on your local network.
